<div class="about">
    <div class="content-policy">
        <img src="src/img/project/logo.png" alt="Logo">
        <h2>TERMINOS LEGALES Y CONDICIONES</h2>
        <p>Usted como usuario, al utilizar éste Sitio Web, acepta los términos y condiciones, que a continuación se mencionan:</p>
        <p>Cualquier uso del material contenido en este sitio web por el usuario “usted” será utilizado bajo su propio riesgo.</p>
        <p>Tropical World no será responsable si la información disponible en este sitio web no es precisa o completa.</p>
        <h2>TRANSMISIÓN</h2>
        <p>Cualquier información que usted transmita o coloque en este sitio web no será considerada como confidencial y se convierte en propiedad de Tropical World y la podrá utilizar para cualquier propósito, incluso para el desarrollo, fabricación, publicación y mercadeo de productos. Cualquier tipo de uso no generará compensación alguna. Usted declara que es el titular o licenciatario del contenido, que de ninguna manera viola derechos de terceros.</p>
        <h2>PROPIEDAD INTELECTUAL</h2>
        <p>A reserve de sus Datos Personales, cualquier información, textos, imágenes, que sea introducido por usted en los espacios disponibles al en general, será propiedad de Tropical World, por lo que éste podrá utilizarla, reproducirla, modificarla, adaptarla o ponerla a disposición del público, además de estar facultado para utilizar los comentarios, ideas, sugerencias o cualquier información que usted introduzca a este sitio, sin que esto genere alguna compensación.</p>
        <p>Por otro lado, Tropical World se reserva el derecho a evitar que se publiquen fotos, gráficos, material sonoro o de video que usted introduzca en los espacios disponibles al público en general, que éste sean ilegales, inmorales, o bien, que vayan en contra de sus políticas. </p>
        <p>Ninguna reproducción de cualquier parte del sitio web puede ser vendida o distribuida con multas de lucro ni debe ser modificada o incorporada en cualquier otro medio. <br>Las marcas, diseños, personajes, caracteres y marcas publicadas en el Sitio Web pertenecen a Tropical World. Ningún contenido de este sitio web debe interpretarse como un otorgamiento de licencia de uso o derecho de uso de cualquier Marca mostrada en este sitio web. Por el acceso a este sitio web, usted se compromete a no reproducir ni utilizar ningún derecho de propiedad industrial e intelectual propiedad de Tropical World sin su autorización. Tropical World hará uso de las acciones legales correspondientes en caso de que se haga un uso ilegal de sus derechos de propiedad industrial e intelectual, incluyendo acciones penales, civiles y administrativas.</p>
        <h2>ENLACES A OTROS SITIOS WEB</h2>
        <p>Los enlaces en los sitios web de Tropical World pueden dirigirlo a sitios web diferentes al de Tropical World, por lo cual Tropical World no acepta alguna responsabilidad con respecto al contenido, precisión o función del contenido de estos otros sitios web.</p>
        <h2>GARANTÍAS</h2>
        <p>Tropical World no otorga garantías de ningún tipo, ni de manera expresa, implícita, legal, ni de ningún otro tipo, (incluyendo garantías implícitas de comercio y aptitud para cualquier propósito) así como tampoco garantías o representaciones que el material en este sitio web esté completo, preciso, puntual y que no infrinja derechos de terceros; que el servicio de este sitio web sea ininterrumpido o libre de errores y seguro; que cualquier consejo u opinión de Tropical World a través de este sitio web es preciso o confiable.Tropical World por medio de éste documento renuncia expresamente a cualquier garantía. En algunas jurisdicciones no se permiten las exclusiones de responsabilidad implícita, por lo que usted deberá verificar si están aplicables a usted.</p>
        <h2>RENUNCIA DE RESPONSABILIDADES</h2>
        <p>Ni Tropical World ni ninguna otra parte involucrada en crear, producir o manejar este sitio en nuestro nombre tendrá alguna responsabilidad por cualquier: uso directo, accidental, consecuente, indirecto, daños, gastos, pérdidas o responsabilidad por su acceso a usar, inhabilitar el uso, cambiar el contenido de este sitio o que surjan por cualquier otro acceso al sitio web a través de un enlace de este sitio web o de cualquier acción que tomemos o decidamos no tomar como resultado de cualquier correo electrónico que nos envíen. <br> Cualquier material contenido en este sitio web está sujeto a cambio sin previo aviso. <br>Adicionalmente, Tropical World no tendrá responsabilidad alguna por cualquier pérdida causada por virus que pueda infectar a su computadora u otra propiedad por razón de usar, ingresar o bajar cualquier material de este sitio web. Si usted elige bajar materiales de este sitio web siempre será bajo su propio riesgo.</p>
        <h2>ACTIVIDADES PROHIBIDAS</h2>
        <p>Se encuentra estrictamente prohibido cometer cualquier acto que a consideración de Tropical World, sea considerado como inapropiado o ilegal incluyendo de manera ilimitada:</p>
        <p>Cualquier acto que pueda constituir una infracción a la privacidad (incluyendo subir información privada sin el consentimiento del dueño de la misma) o cualquier otro que forme parte de los derechos legales de los individuos;</p>
        <p>Usar este sitio web para difamar o calumniar a Tropical World, sus colaboradores o cualquier otro tercero, así como actuar de forma tal que se vea perjudicado Tropical World;</p>
        <p>Subir archivos que contengan virus que puedan causar daño a la propiedad de Tropical World o la propiedad de otros individuos.</p>
        <p>TROPICAL WORLD se reserva el derecho de ejercer o dar por terminado el ingreso a este sitio web en cualquier momento.</p>
        <h2>LEGISLACIÓN Y TRIBUNALES</h2>
        <p>Usted y Tropical World acuerdan que cualquier controversia o reclamo que surja del uso de este sitio web debe ser reglamentado por la Legislación y Tribunales de México Distrito Federal.</p>
        <h2>ACTUALIZACIÓN DE LOS TÉRMINOS Y CONDICIONES</h2>
        <p>Nos reservamos el derecho de hacer cualquier cambio o corregir a estos Términos y Condiciones.</p>
        <h2>TÉRMINOS Y CONDICIONES</h2>
        <p>Como usuario usted acepta los términos y condiciones de este sitio web, mencionados a continuación:</p>
        <p>Cualquier uso que usted haga del material contenido en este sitio web será bajo su propio riesgo.</p>
        <p>Tropical World no será responsable si la información disponible en este sitio web no es precisa o completa.</p>
        <h2>TRANSMISIÓN</h2>
        <p>Cualquier información que transmita o coloque en este sitio web no se considerará confidencial, pasará a ser propiedad de Tropical World y podrá ser utilizada para cualquier propósito, incluido el desarrollo, la fabricación, la publicidad y la comercialización de productos. Cualquier uso de dicha información no generará compensación alguna. Usted declara y garantiza que es el propietario o licenciatario del contenido, que de ninguna manera viola los derechos de terceros.</p>
        <h2>PROPIEDAD INTELECTUAL</h2>
        <p>Con excepción de sus datos personales, cualquier otra información, texto o imágenes que usted suba para llenar los espacios disponibles para el público en general, serán propiedad de Tropical World. Por lo tanto, Tropical World podrá utilizar, reproducir, modificar, adaptar o poner a disposición del público en general dicha información. Asimismo, Tropical World podrá utilizar los comentarios, ideas, sugerencias o cualquier otra información que usted cargue en este sitio web, sin generar compensación alguna.</p>
        <p>Tropical World se reserva el derecho de evitar la publicación de fotografías, gráficos, material de audio o videos subidos por usted para llenar los espacios disponibles para el público en general, que Tropical World considere ilegales, inmorales o contrarios a sus políticas.</p>
        <p>Ninguna reproducción o cualquier parte del sitio web se venderá o distribuirá con fines de lucro ni se modificará o incorporará a ningún otro medio de comunicación. Todas las marcas comerciales, diseños, personajes y marcas publicadas en este sitio web son propiedad en su totalidad de Tropical World. El contenido de este sitio web NO DEBE interpretarse como una concesión de licencia o un derecho de uso de una marca comercial que se muestra en dicho sitio web. Al acceder a este sitio web, usted acepta no reproducir ni utilizar ningún derecho de propiedad industrial e intelectual de Tropical World sin la autorización previa y por escrito de Tropical World. En caso de que no cumpla con lo anterior, Tropical World se reserva el derecho de iniciar las acciones legales correspondientes, incluyendo cualquier acción penal, civil o administrativa.</p>
        <h2>DESCARGO DE RESPONSABILIDAD</h2>
        <p>Ni Tropical World ni ninguna otra parte involucrada en la creación, producción o administración de este sitio en nuestro nombre serán responsables de ningún daño, gasto, pérdida o responsabilidad directa, incidental, consecuente, indirecta por su acceso para usar, deshabilitar el uso, cambiar el contenido de este sitio o que surja de cualquier otro acceso al sitio web a través de un enlace en este sitio web o de cualquier acción que tomemos o decidamos no tomar como resultado de cualquier correo electrónico que enviemos.</p>
        <p>Cualquier material contenido en este sitio web está sujeto a cambios sin previo aviso.</p>
        <p>Adicionalmente, Tropical World no será responsable por ninguna pérdida causada por virus que puedan infectar su computadora u otra propiedad por razón del uso, acceso o descarga de cualquier material de este sitio web. Si elige descargar materiales de este sitio web, será bajo su propio riesgo.</p>
        <h2>JURISDICCIÓN</h2>
        <p>Usted y Tropical World acuerdan que cualquier controversia o reclamo que surja del uso de este sitio web se regirá e interpretará por las leyes de México y se someterá a la jurisdicción exclusiva de los tribunales de la Ciudad de México, México.</p>
        <h2>ACTUALIZACIÓN DE TÉRMINOS Y CONDICIONES</h2>
        <p>Nos reservamos el derecho de actualizar, hacer cualquier cambio o corrección a estos términos y condiciones.</p>
    </div>
</div>